[[plugins]]
repo = 'Shougo/unite.vim'
if = "!has('nvim')"
depends = 'neomru.vim'
on_cmd = ['Unite']
hook_source = '''
  " let g:unite_source_grep_max_candidates = 200
  let g:unite_enable_start_insert = 0
  let g:unite_source_bookmark_directory = expand('~/.unite/bookmark')
 
  " call unite#custom_default_action('source/bookmark/directory' , 'vimfiler')
 
  autocmd myvimrc FileType unite imap <silent><buffer> <C-f> <Plug>(unite_insert_leave)
 
  if executable('ag')
      " Use ag in unite grep source.
      let g:unite_source_grep_command = 'ag'
      let g:unite_source_grep_recursive_opt = ''
      let g:unite_source_grep_default_opts =
      \ '--line-numbers --nocolor --nogroup --hidden --ignore ' .
      \  ' ''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'' '
  endif
'''
hook_add = '''
  nnoremap [unite] <Nop>
  nmap <Leader>u [unite]
  nnoremap <silent> [unite]b :<C-u>Unite<Space>buffer<CR>
  nnoremap <silent> [unite]c :<C-u>Unite<Space>bookmark<CR>
  nnoremap <silent> [unite]y :<C-u>Unite<Space>history/yank<CR>
  nnoremap <silent> [unite]f :<C-u>Unite<Space>file<CR>
  nnoremap <silent> [unite]m :<C-u>Unite<Space>file_mru<CR>
  nnoremap <silent> [unite]a :<C-u>Unite buffer file file_mru bookmark<CR>
  nnoremap <silent> [unite]R :<C-u>Unite<Space>register<CR>
  nnoremap <silent> [unite]r :<C-u>UniteResume search-buffer<CR>
  nnoremap <silent> [unite]g :<C-u>Unite grep:. -buffer-name=search-buffer<CR>
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
depends = 'neomru.vim'
on_cmd = ['Denite']
hook_post_source = '''
	call denite#custom#var('grep', 'command', ['ag'])
  call denite#custom#map('insert', '<C-f>', '<denite:enter_mode:normal>')
  call denite#custom#map('insert', '<Esc>', '<denite:enter_mode:normal>')
'''
hook_add = '''
  nnoremap [denite] <Nop>
  nmap <Leader>d [denite]
  nnoremap <silent> [denite]b :<C-u>Denite<Space>buffer<CR>
  nnoremap <silent> [denite]p :<C-u>Denite<Space>file/rec<CR>
  nnoremap <silent> [denite]m :<C-u>Denite<Space>file_mru<CR>
  nnoremap <silent> [denite]r :<C-u>Denite<Space>register<CR>
  nnoremap <silent> [denite]g :<C-u>Denite<Space>grep<Space>-no-empty<CR>
  nnoremap <silent> [denite]h :<C-u>Denite<Space>help<CR>
  nnoremap <silent> [denite]l :<C-u>Denite<Space>line<CR>
  nnoremap <silent> [denite]f :<C-u>Denite<Space>-buffer-name=search<Space>-resume<CR>
'''
[plugins.ftplugin]
denite = '''
nnoremap <silent><buffer><expr> <CR>
\ denite#do_map('do_action')
nnoremap <silent><buffer><expr> d
\ denite#do_map('do_action', 'delete')
nnoremap <silent><buffer><expr> p
\ denite#do_map('do_action', 'preview')
nnoremap <silent><buffer><expr> q
\ denite#do_map('quit')
nnoremap <silent><buffer><expr> i
\ denite#do_map('open_filter_buffer')
nnoremap <silent><buffer><expr> <Space>
\ denite#do_map('toggle_select').'j'
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
if = "!has('nvim')"
# "depends = 'unite.vim'   this prevents setting filetype, unite.vim can not be set as depends?
on_map = [['n', '<Plug>']]
on_path = '.*'
hook_add = 'noremap <silent> <Leader>f :VimFilerBufferDir -split -simple -winwidth=40 -no-quit<CR>'
hook_source = 'let vimfiler_as_default_explorer = 1'

[[plugins]]
repo = 'glidenote/memolist.vim'
on_cmd = ['MemoNew','MemoList','MemoGrep']
hook_add = '''
  nnoremap <Leader>mn  :MemoNew<CR>
  nnoremap <Leader>ml  :MemoList<CR>
  nnoremap <Leader>mg  :MemoGrep<CR>
'''
hook_source = '''
  let g:memolist_denite = 1
  let g:memolist_path = expand('~/.memo')
'''

[[plugins]]
repo = 'AndrewRadev/linediff.vim'
on_cmd = ['Linediff']

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['Git']
on_event = ['FocusLost', 'CursorHold']
hook_post_source = 'doautoall fugitive BufNewFile'

[[plugins]]
repo = 'joonty/vdebug'
on_ft = 'php'
hook_source = '''
  let g:vdebug_options = {
  \   'path_maps': { '/synced_folders/rpg-server': '/usr/local/funzio/cc-server' }
  \ , 'ide_key': ''
  \}
'''

[[plugins]]
repo = 'stephpy/vim-php-cs-fixer'
on_ft = 'php'
hook_source = '''
  let g:php_cs_fixer_rules = '@PSR2'
  let g:php_cs_fixer_path = '/usr/local/bin/php-cs-fixer'
  nnoremap <silent> <Leader>fix :call PhpCsFixerFixFile()<CR>
'''

[[plugins]]
repo = 'AndrewRadev/switch.vim'
on_cmd = ['Switch']
hook_add = '''
  let g:switch_mapping = ''
  " switch single quoto to double
  let g:switch_custom_definitions = [
  \   {
  \       "'\(\k\+\)'": '"\1"',
  \       '"\(\k\+\)"': "'\1'",
  \   },
  \]
  " switch snake case to camel case
  let g:variable_style_switch_definitions = [
  \   {
  \     '\<[a-z0-9]\+_\k\+\>': {
  \       '_\(.\)': '\U\1'
  \     },
  \     '\<[a-z0-9]\+[A-Z]\k\+\>': {
  \       '\([A-Z]\)': '_\l\1'
  \     },
  \   }
  \]
  nnoremap [switch.vim] <Nop>
  nmap <Leader>sw [switch.vim]
  nnoremap <silent> [switch.vim] :Switch<CR>
  nnoremap <silent> [switch.vim]w :call switch#Switch({'definitions': g:variable_style_switch_definitions})<CR>
'''

[[plugins]]
repo = 'kana/vim-submode'
on_map = ['<C-w>>', '<C-w><', '<C-w>+', '<C-w>-']
hook_source = '''
  call submode#enter_with('winsize', 'n', '', '<C-w>>', '<C-w>>')
  call submode#enter_with('winsize', 'n', '', '<C-w><', '<C-w><')
  call submode#enter_with('winsize', 'n', '', '<C-w>+', '<C-w>+')
  call submode#enter_with('winsize', 'n', '', '<C-w>-', '<C-w>-')
  call submode#map('winsize', 'n', '', '>', '<C-w>>')
  call submode#map('winsize', 'n', '', '<', '<C-w><')
  call submode#map('winsize', 'n', '', '+', '<C-w>+')
  call submode#map('winsize', 'n', '', '-', '<C-w>-')
'''

[[plugins]]
repo = 't9md/vim-choosewin'
on_map = [['n', '<Plug>']]
hook_add = 'nmap  <Leader>w  <Plug>(choosewin)'
hook_source = '''
  let g:choosewin_overlay_enable = 1
  let g:choosewin_overlay_clear_multibyte = 1
  let g:choosewin_color_overlay = {
        \ 'gui': ['DodgerBlue3', 'DodgerBlue3' ],
        \ 'cterm': [ 25, 25 ]
        \ }
  let g:choosewin_color_overlay_current = {
        \ 'gui': ['firebrick1', 'firebrick1' ],
        \ 'cterm': [ 124, 124 ]
        \ }
  let g:choosewin_blink_on_land      = 0
  let g:choosewin_statusline_replace = 0
  let g:choosewin_tabline_replace    = 0
'''

[[plugins]]
repo = 'vim-scripts/yanktmp.vim'
on_map = [['n', '<Plug>']]
hook_add = '''
  nnoremap <silent> <Leader>ty :call YanktmpYank()<CR>
  nnoremap <silent> <Leader>tp :call YanktmpPaste_p()<CR>
  nnoremap <silent> <Leader>tP :call YanktmpPaste_P()<CR>
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = '<Plug>(EasyAlign'
hook_add = '''
  xmap <Enter> <Plug>(EasyAlign)
  nmap <Leader>a <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'rking/ag.vim'
on_cmd = ['Ag', 'AgFile']

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
on_map = [['n', '<Leader>p']]
hook_add = '''
  let g:ctrlp_map = '<Leader>p'
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = [['n', '<Plug>']]
hook_add = '''
nmap <silent> <Leader>rr :cclose<CR>:write<CR><Plug>(quickrun)<CR>
nmap <silent> <Leader>ri :cclose<CR>:write<CR>:QuickRun -input input.txt -runner system<CR>
nmap <silent> <Leader>re :cclose<CR>:write<CR>:QuickRun -input input.txt -runner system -command 'clang++' -cmdopt '-std=c++17 -stdlib=libc++ -Wall -O2 -D_DEBUG'<CR>
'''
hook_source = '''
   let g:quickrun_config = {
   \   '_': {
   \     'input': '=%{b:input}', 'cmdopt': '%{b:cmdopt}', 'args': '%{b:args}',
   \     'runner': 'vimproc',
   \     'runner/vimproc/updatetime': 50,
   \     'outputter' : 'error',
   \     'outputter/buffer/opener' : 'new',
   \     'outputter/buffer/close_on_empty' : 1,
   \     'outputter/buffer/running_mark' : 'running...',
   \     'outputter/error/success' : 'buffer',
   \     'outputter/error/error'   : 'quickfix',
   \     'hook/time/enable': 1,
   \   },
   \   'haskell': {
   \     'command': 'runghc',
   \   },
   \   'python.pytest': {
   \     'command': 'pytest',
   \     'cmdopt': '-s -v',
   \     'outputter/error/error': 'buffer',
   \   },
   \   'cpp': {
   \     'command': 'clang++',
   \     'cmdopt': '-std=c++17 -stdlib=libc++ -Wall -O2',
   \   },
   \}
   " \     'command': 'g++-11',
   " \     'cmdopt': '-std=gnu++17 -Wall -Wextra -O2',
'''

[[plugins]]
repo = 'dag/vim2hs'
on_ft = ['haskell']
on_event = ['FocusLost', 'CursorHold']
hook_source = 'let g:haskell_conceal = 0'

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = ['haskell']
on_event = ['FocusLost', 'CursorHold']
hook_add = '''
  let g:haskellmode_completion_ghc = 0
  let g:necoghc_enable_detailed_browse = 1
  autocmd myvimrc FileType haskell setlocal omnifunc=necoghc#omnifunc
'''

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = ['haskell']
on_event = ['FocusLost', 'CursorHold']
hook_source = '''
  noremap <silent> <Leader>ghi :GhcModTypeInsert<CR>
  noremap <silent> <Leader>ghs :GhcModSplitFunCase<CR>
  noremap <silent> <Leader>ght :GhcModType<CR>
  noremap <silent> <Leader>ghc :GhcModTypeClear<CR>
'''

[[plugins]]
repo = 'thinca/vim-ref'
on_event = ['FocusLost', 'CursorHold']

[[plugins]]
repo = 'ujihisa/ref-hoogle'
on_ft = ['haskell']
on_event = ['FocusLost', 'CursorHold']

[[plugins]]
repo = 'ujihisa/unite-haskellimport'
on_ft = ['haskell']
on_event = ['FocusLost', 'CursorHold']
hook_add = 'nnoremap <buffer> <space>I :<C-u>UniteWithCursorWord haskellimport<Cr>'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['js']
on_event = ['FocusLost', 'CursorHold']

[[plugins]]
repo = 'briancollins/vim-jst'
on_ft = ['js']
on_event = ['FocusLost', 'CursorHold']

[[plugins]]
repo = 'mattn/webapi-vim'
on_ft = ['markdown']

[[plugins]]
repo = 'moznion/hateblo.vim'
depends = ['webapi-vim']
on_ft = ['markdown']

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = ['PrevimOpen']
on_ft = ['markdown']
hook_add = '''
  let g:previm_open_cmd = 'open -a Firefox'
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1
depends = 'neosnippet-snippets'
hook_source = '''
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)

imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

if has('conceal')
  set conceallevel=2 concealcursor=niv
endif
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'tpope/vim-speeddating'
on_event = ['FocusLost', 'CursorHold']

[[plugins]]
repo = 'tpope/vim-repeat'
on_event = ['FocusLost', 'CursorHold']

[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = ['cpp']

[[plugins]]
repo = 'osyo-manga/vim-reunions'
on_source = ['vim-marching']

[[plugins]]
repo = 'osyo-manga/vim-marching'
on_ft = ['cpp', 'c']
on_event = ['FocusLost', 'CursorHold']
hook_add = '''
  let g:marching_enable_neocomplete = 1
'''

[[plugins]]
repo = 'vim-scripts/dbext.vim'
on_event = ['FocusLost', 'CursorHold']

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'Shougo/defx.nvim'
if = "has('nvim')"
hook_add = '''
nnoremap <silent>   <Leader>f
\ :<C-u>Defx -listed -resume -buffer-name=tab`tabpagenr()`<CR>
'''
hook_source = '''
call defx#custom#column('mark', {
        \ 'readonly_icon': '✗',
        \ 'selected_icon': '✓',
        \ })
call defx#custom#column('icon', {
        \ 'directory_icon': '▸',
        \ 'opened_icon': '▾',
        \ 'root_icon': ' ',
        \ })
'''
[plugins.ftplugin]
defx = '''
" Define mappings
nnoremap <silent><buffer><expr> <CR>
\ defx#async_action('drop')
nnoremap <silent><buffer><expr> c
\ defx#do_action('copy')
nnoremap <silent><buffer><expr> !
\ defx#do_action('execute_command')
nnoremap <silent><buffer><expr> m
\ defx#do_action('move')
nnoremap <silent><buffer><expr> p
\ defx#do_action('paste')
nnoremap <silent><buffer><expr> l
\ defx#async_action('open')
nnoremap <silent><buffer><expr> E
\ defx#do_action('open', 'vsplit')
nnoremap <silent><buffer><expr> P
\ defx#do_action('open', 'pedit')
nnoremap <silent><buffer><expr> o
\ defx#async_action('open_or_close_tree')
nnoremap <silent><buffer><expr> O
\ defx#async_action('open_tree_recursive')
nnoremap <silent><buffer><expr> K
\ defx#do_action('new_directory')
nnoremap <silent><buffer><expr> N
\ defx#do_action('new_file')
nnoremap <silent><buffer><expr> M
\ defx#do_action('new_multiple_files')
nnoremap <silent><buffer><expr> C
\ defx#do_action('toggle_columns', 'mark:filename:type:size:time')
nnoremap <silent><buffer><expr> S
\ defx#do_action('toggle_sort', 'Time')
nnoremap <silent><buffer><expr> se
\ defx#do_action('add_session')
nnoremap <silent><buffer><expr> sl
\ defx#do_action('load_session')
nnoremap <silent><buffer><expr> d
\ defx#do_action('remove_trash')
nnoremap <silent><buffer><expr> r
\ defx#do_action('rename')
nnoremap <silent><buffer><expr> x
\ defx#do_action('execute_system')
nnoremap <silent><buffer><expr> >
\ defx#do_action('toggle_ignored_files')
nnoremap <silent><buffer><expr> .
\ defx#do_action('repeat')
nnoremap <silent><buffer><expr> yy
\ defx#do_action('yank_path')
nnoremap <silent><buffer><expr> h
\ defx#async_action('cd', ['..'])
nnoremap <silent><buffer><expr> ~
\ defx#async_action('cd')
nnoremap <silent><buffer><expr> \
\ defx#do_action('cd', getcwd())
nnoremap <silent><buffer><expr> q
\ defx#do_action('quit')
nnoremap <silent><buffer><expr> <Space>
\ defx#do_action('toggle_select') . 'j'
nnoremap <silent><buffer><expr> *
\ defx#do_action('toggle_select_all')
nnoremap <silent><buffer><expr> j
\ line('.') == line('$') ? 'gg' : 'j'
nnoremap <silent><buffer><expr> k
\ line('.') == 1 ? 'G' : 'k'
nnoremap <silent><buffer><expr> <C-l>
\ defx#do_action('redraw')
xnoremap <silent><buffer><expr> <CR>
\ defx#do_action('toggle_select_visual')
nnoremap <silent><buffer><expr> <C-g>
\ defx#do_action('print')
nnoremap <silent><buffer><expr> <Tab> winnr('$') != 1 ?
\ ':<C-u>wincmd w<CR>' :
\ ':<C-u>Defx -buffer-name=temp -split=vertical<CR>'
'''


[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tyru/open-browser-github.vim'
depends = 'open-browser.vim'
